### ISSUE TITLE
Update Job Histroy in /About-Us

### ISSUE THREAD

**Issue by KimangKhenng** [tfd-ed/tfd-blog#149]
### Issue:
The job history is outdated, we need to update it.
### To-do:
- Add the latest job to the job history array in about-us page
- Modify for other language too
### Reference:
- EN: https://github.com/tfd-ed/tfd-blog/blob/develop/content/en/about-us.md
- KM: https://github.com/tfd-ed/tfd-blog/blob/develop/content/km/about-us.md

**Comment by tfd-ed** [comment]
LGTM, go ahead
